Parameters:
  CodeBuildName:
    Type: String
    Default: demo-codebuild
    AllowedPattern: "[A-Za-z0-9-]+"
Resources:
  DeveloperA:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: member
      UserName: Dev-A
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  DeveloperB:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: member
      UserName: Dev-B
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  LeadDev:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: lead
      UserName: Lead-Developer
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  Developers:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: DEVELOPERS
  Leaders:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: LEADERS
  QA:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: QA
      UserName: QA
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  QualityAssurance:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: QualityAssurance
  TambahkanDevelopers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Developers
      Users:
      - !Ref DeveloperA
      - !Ref DeveloperB
  TambahkanLeaders:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Leaders
      Users:
      - !Ref LeadDev
  TambahQA:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref QualityAssurance
      Users:
      - !Ref QA
  DemoCodeCommitDev:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Kode program untuk diskusi CodeCommit.
      RepositoryName: demo-codecommit-dev
      Tags: 
        - Key: department
          Value: demo
  DemoCodeCommitProd:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Kode program untuk diskusi CodeCommit.
      RepositoryName: demo-codecommit-prod
      Tags: 
        - Key: department
          Value: demo
  AturanQA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AturanQA
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:GetPipeline
              - codepipeline:GetPipelineState
              - codepipeline:GetPipelineExecution
              - codepipeline:ListPipelineExecutions
              - codepipeline:ListPipelines
              - codepipeline:PutApprovalResult
            Resource: "*"
      Groups:
        - !Ref QualityAssurance
  AturanDevelopers:
    Type: AWS::IAM::Policy
    DependsOn: DemoCodeCommitDev
    Properties:
      PolicyName: AturanDevelopers
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codecommit:ListRepositories
            Resource: '*'
          - Effect: Allow
            Action:
              - codecommit:Describe*
              - codecommit:Get*
              - codecommit:List*
              - codecommit:GitPull
            Resource: arn:aws:codecommit:ap-southeast-1:623127157773:demo-repository
          - Effect: Allow
            Action:
              - codecommit:GitPush
              - codecommit:CreatePullRequest
            Resource: arn:aws:codecommit:ap-southeast-1:623127157773:demo-repository
            Condition:
              StringNotEqualsIfExists:
                codecommit:References:
                - refs/heads/master
          - Effect: Allow
            Action:
              - iam:CreateLoginProfile
              - iam:CreateServiceSpecificCredential
              - iam:ListSSHPublicKeys
              - iam:GetSSHPublicKey
              - iam:ListUserPolicies
              - iam:GetLoginProfile
              - iam:CreateAccessKey
              - iam:ListAccessKeys
              - iam:UpdateAccessKey 
              - iam:ListServiceSpecificCredentials
            Resource:
              - arn:aws:iam::623127157773:user/Dev-A
              - arn:aws:iam::623127157773:user/Dev-B
          - Effect: Allow
            Action:
              - iam:GenerateCredentialReport
              - iam:GetServiceLastAccessedDetailsWithEntities
              - iam:ListAccountAliases
              - iam:ListRoles
              - iam:GetCredentialReport
              - iam:GetServiceLastAccessedDetails
              - iam:GetAccountAuthorizationDetails
              - iam:GetAccountSummary
              - iam:ResetServiceSpecificCredential
              - iam:DeleteServiceSpecificCredential
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:ListUsers
            Resource: '*'
      Groups:
        - !Ref Developers
  AturanLeadDev:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AturanLeadDev
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codecommit:ListRepositoriesForApprovalRuleTemplate
              - codecommit:CreateApprovalRuleTemplate
              - codecommit:UpdateApprovalRuleTemplateName
              - codecommit:GetApprovalRuleTemplate
              - codecommit:ListApprovalRuleTemplates
              - codecommit:DeleteApprovalRuleTemplate
              - codecommit:ListRepositories
              - codecommit:UpdateApprovalRuleTemplateContent
              - codecommit:UpdateApprovalRuleTemplateDescription
              - codecommit:Merge* 
            Resource: '*'
          - Effect: Allow
            Action: codecommit:*
            Resource: arn:aws:codecommit:ap-southeast-1:623127157773:demo-repository
          - Effect: Allow
            Action: 
            - codepipeline:GetPipeline
            - codepipeline:GetPipelineState
            - codepipeline:GetPipelineExecution
            - codepipeline:ListPipelineExecutions
            - codepipeline:ListActionExecutions
            - codepipeline:ListActionTypes
            - codepipeline:ListPipelines
            - codepipeline:ListTagsForResource
            Resource: '*'
          - Effect: Allow
            Action: 
            - codepipeline:*
            Resource: arn:aws:codecommit:ap-southeast-1:623127157773:diskusi-CodeCommit
          - Effect: Allow
            Action:
              - iam:ListUsers
            Resource: '*'
          - Effect: Allow
            Action:
            - iam:ListAccessKeys
            - iam:ListSSHPublicKeys
            - iam:GetLoginProfile
            - iam:DeleteSSHPublicKey
            - iam:GetSSHPublicKey
            - iam:ListSSHPublicKeys
            - iam:UpdateSSHPublicKey
            - iam:UploadSSHPublicKey
            - iam:GetAccountSummary
            Resource: arn:aws:iam::623127157773:user/Lead-Developer
      Groups:
        - !Ref Leaders
  S3UntukCodePipeline:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-untuk-codepipeline
      Tags: 
        - Key: department
          Value: demo
  DemoCodePipeline:
    DependsOn: S3UntukCodePipeline
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: diskusi-CodeCommit
      RoleArn: arn:aws:iam::623127157773:role/service-role/AWSCodePipelineServiceRole-ap-southeast-1-Unsimple-Hello-World
      ArtifactStore:
        Type: S3
        Location: bucket-untuk-codepipeline
      Stages:
        - Name: SourceDev
          Actions:
          - Name: DevSource
            ActionTypeId:
              Category: Source
              Owner: AWS
              Version: 1
              Provider: CodeCommit
            OutputArtifacts:
            - Name: SourceCodeDev
            Configuration:
              RepositoryName: demo-codecommit-dev
              BranchName: main
            RunOrder: 1
        - Name: DevelopmentDeployment
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CodeDeploy
            InputArtifacts:
              - Name: SourceCodeDev
            Configuration:
              ApplicationName: !Ref Application
              DeploymentGroupName: !Ref DeploymentGroupDev
            RunOrder: 2
        - Name: ApprovalToProduction
          Actions:
            - Name: QA
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              RunOrder: 3
        - Name: ProductionDeployment
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CodeDeploy
            InputArtifacts:
              - Name: SourceCodeDev
            Configuration:
              ApplicationName: !Ref Application
              DeploymentGroupName: !Ref DeploymentGroupProd
            RunOrder: 24
  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup untuk EC2.
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
  
  EC2Dev:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: demo-ec2-role
      ImageId: ami-0f62d9254ca98e1aa
      InstanceType: t2.nano
      KeyName: demoKeyPair
      SecurityGroups: 
        - !Ref SecurityGroupEC2
      Tags: 
        - Key: environment
          Value: development
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo yum update
            sudo yum install ruby -y
            sudo yum install wget -y
            wget https://aws-codedeploy-ap-southeast-1.s3.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto
            sudo service codedeploy-agent status
  EC2Prod:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: demo-ec2-role
      ImageId: ami-0f62d9254ca98e1aa
      InstanceType: t2.nano
      KeyName: demoKeyPair
      SecurityGroups: 
        - !Ref SecurityGroupEC2
      Tags: 
        - Key: environment
          Value: production
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo yum update
            sudo yum install ruby -y
            sudo yum install wget -y
            wget https://aws-codedeploy-ap-southeast-1.s3.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto
            sudo service codedeploy-agent status

  CodeDeployIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codedeploy.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole'
  
  Application:
    Type: "AWS::CodeDeploy::Application"
  DeploymentGroupDev:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: !Ref Application
      Ec2TagFilters:
        - Key: environment
          Type: KEY_AND_VALUE
          Value: development
      ServiceRoleArn: !Sub '${CodeDeployIAMRole.Arn}'
  DeploymentGroupProd:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: !Ref Application
      Ec2TagFilters:
        - Key: environment
          Type: KEY_AND_VALUE
          Value: production
      ServiceRoleArn: !Sub '${CodeDeployIAMRole.Arn}'