Resources:
  AturanUntukDevelopers:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AturanDevelopers
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codecommit:BatchGet*
              - codecommit:BatchDescribe*
              - codecommit:Describe*
              - codecommit:EvaluatePullRequestApprovalRules
              - codecommit:Get*
              - codecommit:List*
              - codecommit:GitPull
            Resource: '*'
      Groups:
        - !Ref Developers
  Developers:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: DEVELOPERS
  Leaders:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: LEADERS
  TambahkanDevelopers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Developers
      Users:
      - !Ref DeveloperA
      - !Ref DeveloperB
  TambahkanLeaders:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Leaders
      Users:
      - !Ref LeadDev
  DeveloperA:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: member
      UserName: Dev-A
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  DeveloperB:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: member
      UserName: Dev-B
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  LeadDev:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: lead
      UserName: Lead-Developer
      LoginProfile:
          Password: KataSandinyaSangatRahasia123456
          PasswordResetRequired: False
  QA:
    Type: AWS::IAM::User
    Properties: 
      Tags: 
        - Key: role
          Value: QA
      UserName: QA